import { City, Event } from '@/types';

export const cities: City[] = [
  {
    id: '1',
    rank: 1,
    name: '제주도',
    nameEn: 'Jeju',
    slug: 'jeju',
    image: '/images/jeju.jpg',
    rating: 4.7,
    lovePercentage: 89,
    activeNomads: 156,
    ratings: {
      cafe: 4.8,
      housing: 3.5,
      transportation: 3.2,
      food: 4.6,
      nature: 5.0,
    },
    costOfLiving: {
      min: 155,
      max: 225,
    },
    internetSpeed: 95,
    cafes24h: 12,
    weather: {
      temp: 18,
      condition: '맑음',
    },
  },
  {
    id: '2',
    rank: 2,
    name: '부산',
    nameEn: 'Busan',
    slug: 'busan',
    image: '/images/busan.jpg',
    rating: 4.5,
    lovePercentage: 85,
    activeNomads: 203,
    ratings: {
      cafe: 4.5,
      housing: 4.0,
      transportation: 4.5,
      food: 4.7,
      nature: 4.3,
    },
    costOfLiving: {
      min: 120,
      max: 180,
    },
    internetSpeed: 120,
    cafes24h: 18,
    weather: {
      temp: 16,
      condition: '흐림',
    },
  },
  {
    id: '3',
    rank: 3,
    name: '강릉',
    nameEn: 'Gangneung',
    slug: 'gangneung',
    image: '/images/gangneung.jpg',
    rating: 4.3,
    lovePercentage: 82,
    activeNomads: 87,
    ratings: {
      cafe: 4.6,
      housing: 3.8,
      transportation: 3.0,
      food: 4.2,
      nature: 4.8,
    },
    costOfLiving: {
      min: 100,
      max: 150,
    },
    internetSpeed: 85,
    cafes24h: 8,
    weather: {
      temp: 14,
      condition: '맑음',
    },
  },
  {
    id: '4',
    rank: 4,
    name: '경주',
    nameEn: 'Gyeongju',
    slug: 'gyeongju',
    image: '/images/gyeongju.jpg',
    rating: 4.2,
    lovePercentage: 78,
    activeNomads: 45,
    ratings: {
      cafe: 4.0,
      housing: 4.2,
      transportation: 3.5,
      food: 4.3,
      nature: 4.5,
    },
    costOfLiving: {
      min: 90,
      max: 140,
    },
    internetSpeed: 80,
    cafes24h: 5,
    weather: {
      temp: 15,
      condition: '맑음',
    },
  },
  {
    id: '5',
    rank: 5,
    name: '전주',
    nameEn: 'Jeonju',
    slug: 'jeonju',
    image: '/images/jeonju.jpg',
    rating: 4.1,
    lovePercentage: 76,
    activeNomads: 72,
    ratings: {
      cafe: 4.4,
      housing: 4.3,
      transportation: 3.8,
      food: 4.9,
      nature: 3.8,
    },
    costOfLiving: {
      min: 95,
      max: 145,
    },
    internetSpeed: 90,
    cafes24h: 7,
    weather: {
      temp: 13,
      condition: '흐림',
    },
  },
];

export const events: Event[] = [
  {
    id: '1',
    title: '제주 디지털 노마드 네트워킹',
    cityId: '1',
    cityName: '제주도',
    date: new Date('2025-10-05'),
    participants: 23,
    maxParticipants: 30,
    type: 'networking',
  },
  {
    id: '2',
    title: '부산 코딩 모임',
    cityId: '2',
    cityName: '부산',
    date: new Date('2025-10-07'),
    participants: 15,
    maxParticipants: 20,
    type: 'meetup',
  },
  {
    id: '3',
    title: '강릉 워케이션 워크샵',
    cityId: '3',
    cityName: '강릉',
    date: new Date('2025-10-10'),
    participants: 8,
    maxParticipants: 15,
    type: 'workshop',
  },
];

export const totalMembers = 2847;
export const totalCities = 32;
export const activeNow = 156;
