import { City, Event, Review, User, Comment } from '@/types';

export const cities: City[] = [
  {
    id: '1',
    rank: 1,
    name: '제주도',
    nameEn: 'Jeju',
    slug: 'jeju',
    image: '/images/jeju.jpg',
    rating: 4.7,
    lovePercentage: 89,
    activeNomads: 156,
    ratings: {
      cafe: 4.8,
      housing: 3.5,
      transportation: 3.2,
      food: 4.6,
      nature: 5.0,
    },
    costOfLiving: {
      min: 155,
      max: 225,
    },
    internetSpeed: 95,
    cafes24h: 12,
    weather: {
      temp: 18,
      condition: '맑음',
    },
  },
  {
    id: '2',
    rank: 2,
    name: '부산',
    nameEn: 'Busan',
    slug: 'busan',
    image: '/images/busan.jpg',
    rating: 4.5,
    lovePercentage: 85,
    activeNomads: 203,
    ratings: {
      cafe: 4.5,
      housing: 4.0,
      transportation: 4.5,
      food: 4.7,
      nature: 4.3,
    },
    costOfLiving: {
      min: 120,
      max: 180,
    },
    internetSpeed: 120,
    cafes24h: 18,
    weather: {
      temp: 16,
      condition: '흐림',
    },
  },
  {
    id: '3',
    rank: 3,
    name: '강릉',
    nameEn: 'Gangneung',
    slug: 'gangneung',
    image: '/images/gangneung.jpg',
    rating: 4.3,
    lovePercentage: 82,
    activeNomads: 87,
    ratings: {
      cafe: 4.6,
      housing: 3.8,
      transportation: 3.0,
      food: 4.2,
      nature: 4.8,
    },
    costOfLiving: {
      min: 100,
      max: 150,
    },
    internetSpeed: 85,
    cafes24h: 8,
    weather: {
      temp: 14,
      condition: '맑음',
    },
  },
  {
    id: '4',
    rank: 4,
    name: '경주',
    nameEn: 'Gyeongju',
    slug: 'gyeongju',
    image: '/images/gyeongju.jpg',
    rating: 4.2,
    lovePercentage: 78,
    activeNomads: 45,
    ratings: {
      cafe: 4.0,
      housing: 4.2,
      transportation: 3.5,
      food: 4.3,
      nature: 4.5,
    },
    costOfLiving: {
      min: 90,
      max: 140,
    },
    internetSpeed: 80,
    cafes24h: 5,
    weather: {
      temp: 15,
      condition: '맑음',
    },
  },
  {
    id: '5',
    rank: 5,
    name: '전주',
    nameEn: 'Jeonju',
    slug: 'jeonju',
    image: '/images/jeonju.jpg',
    rating: 4.1,
    lovePercentage: 76,
    activeNomads: 72,
    ratings: {
      cafe: 4.4,
      housing: 4.3,
      transportation: 3.8,
      food: 4.9,
      nature: 3.8,
    },
    costOfLiving: {
      min: 95,
      max: 145,
    },
    internetSpeed: 90,
    cafes24h: 7,
    weather: {
      temp: 13,
      condition: '흐림',
    },
  },
];

export const events: Event[] = [
  {
    id: '1',
    title: '제주 디지털 노마드 네트워킹',
    titleEn: 'Jeju Digital Nomad Networking',
    description: '제주도에서 활동하는 디지털 노마드들과 함께하는 네트워킹 이벤트입니다. 다양한 직군의 노마드들을 만나 정보를 공유하고 인사이트를 얻어가세요!',
    descriptionEn: 'Networking event for digital nomads in Jeju. Meet nomads from various fields and share insights!',
    type: 'networking',
    city: '제주도',
    citySlug: 'jeju',
    location: {
      name: '제주시 노형동 코워킹 스페이스',
      address: '제주특별자치도 제주시 노형동'
    },
    date: new Date('2025-10-15'),
    startTime: '14:00',
    endTime: '17:00',
    capacity: 30,
    registered: 23,
    organizer: {
      id: 'user-1',
      name: '김지은',
      avatar: '/avatars/user1.jpg'
    },
    image: '/images/event1.jpg',
  },
  {
    id: '2',
    title: '부산 코딩 모임',
    titleEn: 'Busan Coding Meetup',
    description: '프론트엔드 개발자들을 위한 코딩 모임입니다. React, Next.js 등 최신 기술 스택을 공유하고 함께 성장해요.',
    descriptionEn: 'Coding meetup for frontend developers. Share and learn React, Next.js and more!',
    type: 'meetup',
    city: '부산',
    citySlug: 'busan',
    location: {
      name: '해운대 해변 카페',
      address: '부산광역시 해운대구 해운대해변로'
    },
    date: new Date('2025-10-18'),
    startTime: '10:00',
    endTime: '13:00',
    capacity: 20,
    registered: 15,
    organizer: {
      id: 'user-2',
      name: '박민수',
      avatar: '/avatars/user2.jpg'
    },
    image: '/images/event2.jpg',
  },
  {
    id: '3',
    title: '강릉 워케이션 워크샵',
    titleEn: 'Gangneung Workation Workshop',
    description: '강릉에서 워케이션을 즐기며 생산성 향상 방법을 배우는 워크샵입니다. 실무에 바로 적용할 수 있는 팁들을 제공합니다.',
    descriptionEn: 'Learn productivity tips while enjoying a workation in Gangneung.',
    type: 'workshop',
    city: '강릉',
    citySlug: 'gangneung',
    location: {
      name: '강릉 카페거리',
      address: '강원도 강릉시 창해로'
    },
    date: new Date('2025-10-20'),
    startTime: '15:00',
    endTime: '18:00',
    capacity: 15,
    registered: 8,
    organizer: {
      id: 'user-3',
      name: '이수진',
      avatar: '/avatars/user3.jpg'
    },
    image: '/images/event3.jpg',
  },
  {
    id: '4',
    title: '부산 사진 워크샵',
    titleEn: 'Busan Photography Workshop',
    description: '여행 사진 촬영 기법을 배우는 워크샵입니다. 프로 사진작가와 함께 부산의 명소를 돌며 실습해요.',
    descriptionEn: 'Learn travel photography techniques with a professional photographer.',
    type: 'workshop',
    city: '부산',
    citySlug: 'busan',
    location: {
      name: '광안리 해변',
      address: '부산광역시 수영구 광안해변로'
    },
    date: new Date('2025-10-22'),
    startTime: '09:00',
    endTime: '12:00',
    capacity: 15,
    registered: 12,
    organizer: {
      id: 'user-4',
      name: '최현우',
      avatar: '/avatars/user4.jpg'
    },
    image: '/images/event4.jpg',
  },
  {
    id: '5',
    title: '제주 스타트업 밋업',
    titleEn: 'Jeju Startup Meetup',
    description: '스타트업에 관심있는 노마드들의 모임입니다. 창업 아이디어를 공유하고 협업 기회를 찾아보세요.',
    descriptionEn: 'Meetup for nomads interested in startups. Share ideas and find collaboration opportunities!',
    type: 'networking',
    city: '제주도',
    citySlug: 'jeju',
    location: {
      name: '제주창조경제혁신센터',
      address: '제주특별자치도 제주시 첨단로'
    },
    date: new Date('2025-10-25'),
    startTime: '16:00',
    endTime: '19:00',
    capacity: 25,
    registered: 18,
    organizer: {
      id: 'user-5',
      name: '정다은',
      avatar: '/avatars/user5.jpg'
    },
    image: '/images/event5.jpg',
  },
];

export const users: User[] = [
  {
    id: 'user-1',
    name: '김지은',
    avatar: '/avatars/user1.jpg',
    bio: '프리랜서 디자이너로 제주도에서 워케이션 중입니다.',
    currentCity: '제주도',
    joinedDate: new Date('2024-03-15'),
    reviewCount: 8,
    eventCount: 5,
  },
  {
    id: 'user-2',
    name: '박민수',
    avatar: '/avatars/user2.jpg',
    bio: '풀스택 개발자. 부산에서 원격근무하며 살고 있어요.',
    currentCity: '부산',
    joinedDate: new Date('2024-05-20'),
    reviewCount: 12,
    eventCount: 7,
  },
  {
    id: 'user-3',
    name: '이수진',
    avatar: '/avatars/user3.jpg',
    bio: '콘텐츠 크리에이터. 강릉의 자연을 사랑합니다.',
    currentCity: '강릉',
    joinedDate: new Date('2024-07-10'),
    reviewCount: 5,
    eventCount: 3,
  },
  {
    id: 'user-4',
    name: '최현우',
    avatar: '/avatars/user4.jpg',
    bio: '프로 사진작가이자 여행 블로거입니다.',
    currentCity: '부산',
    joinedDate: new Date('2024-01-05'),
    reviewCount: 15,
    eventCount: 10,
  },
  {
    id: 'user-5',
    name: '정다은',
    avatar: '/avatars/user5.jpg',
    bio: '스타트업 창업자. 제주도에서 새로운 도전을 준비중이에요.',
    currentCity: '제주도',
    joinedDate: new Date('2024-08-12'),
    reviewCount: 6,
    eventCount: 4,
  },
];

export const reviews: Review[] = [
  {
    id: 'review-1',
    cityId: '1',
    userId: 'user-1',
    userName: '김지은',
    userAvatar: '/avatars/user1.jpg',
    rating: 5,
    title: '제주도는 디지털 노마드의 천국!',
    stayDuration: '3개월',
    content: '제주도에서 3개월간 워케이션을 했는데 정말 최고였어요. 카페 인프라가 잘 되어있고, 자연 경관이 아름다워서 일할 때 힐링이 됩니다. 다만 생활비가 조금 비싼 편이에요.',
    createdAt: new Date('2025-09-20'),
    helpful: 24,
    helpfulBy: ['user-2', 'user-3'],
  },
  {
    id: 'review-2',
    cityId: '2',
    userId: 'user-2',
    userName: '박민수',
    userAvatar: '/avatars/user2.jpg',
    rating: 4,
    title: '부산 해운대에서의 워케이션',
    stayDuration: '2개월',
    content: '해운대 근처에서 살면서 일했는데 바다를 보며 일하는 게 너무 좋았어요. 교통도 편리하고 먹거리도 다양합니다. 다만 여름에는 관광객이 너무 많아요.',
    createdAt: new Date('2025-09-15'),
    helpful: 18,
    helpfulBy: ['user-1'],
  },
  {
    id: 'review-3',
    cityId: '3',
    userId: 'user-3',
    userName: '이수진',
    userAvatar: '/avatars/user3.jpg',
    rating: 5,
    title: '강릉 커피 투어하며 일하기',
    stayDuration: '1개월',
    content: '강릉은 커피의 도시답게 카페가 정말 많아요. 매일 다른 카페에서 일하는 재미가 쏠쏠합니다. 조용하고 평화로운 분위기가 집중하기 좋아요.',
    createdAt: new Date('2025-09-10'),
    helpful: 15,
    helpfulBy: [],
  },
  {
    id: 'review-4',
    cityId: '1',
    userId: 'user-4',
    userName: '최현우',
    userAvatar: '/avatars/user4.jpg',
    rating: 4,
    title: '제주도 서귀포 지역 추천',
    stayDuration: '6개월',
    content: '제주시보다 서귀포 쪽이 조용하고 집중하기 좋습니다. 렌터카는 필수이고, 자연 속에서 힐링하며 일하고 싶다면 강력 추천합니다!',
    createdAt: new Date('2025-09-05'),
    helpful: 21,
    helpfulBy: ['user-2', 'user-5'],
  },
];

export const comments: Comment[] = [
  {
    id: 'comment-1',
    reviewId: 'review-1',
    userId: 'user-2',
    userName: '박민수',
    userAvatar: '/avatars/user2.jpg',
    content: '저도 제주도에서 일해봤는데 공감돼요! 특히 날씨 좋을 때 바다 근처 카페에서 일하면 정말 최고죠.',
    createdAt: new Date('2025-09-21'),
  },
  {
    id: 'comment-2',
    reviewId: 'review-1',
    userId: 'user-3',
    userName: '이수진',
    userAvatar: '/avatars/user3.jpg',
    content: '생활비가 비싸다는 부분 동의해요. 그래도 가치는 충분하다고 생각합니다!',
    createdAt: new Date('2025-09-22'),
  },
  {
    id: 'comment-3',
    reviewId: 'review-1',
    userId: 'user-1',
    userName: '김지은',
    userAvatar: '/avatars/user1.jpg',
    content: '감사합니다! 저도 다시 가고 싶네요 ㅎㅎ',
    createdAt: new Date('2025-09-23'),
    parentId: 'comment-2',
  },
  {
    id: 'comment-4',
    reviewId: 'review-2',
    userId: 'user-5',
    userName: '정다은',
    userAvatar: '/avatars/user5.jpg',
    content: '부산 정보 감사합니다! 다음 달에 부산 가는데 참고할게요.',
    createdAt: new Date('2025-09-16'),
  },
];

export const totalMembers = 2847;
export const totalCities = 32;
export const activeNow = 156;
